### PR TITLE
add single quotes on auth header for curl

### PR DESCRIPTION
**Pull request by barelyhuman**
done since the auth header isn't being considered as a single string
on shell while executing 

Which ends up returing 401 
Screenshot 2021-12-04 at 2 02 44 PM

==TBD==
- [ ] Test on Linux env to check for behavioural difference

### CODE REVIEW

**Comment by egoist** [comment]
adding a single quote makes curl simply ignore that header in my test 🥲

**Comment by egoist** [comment]
adding a single quote makes curl simply ignore that header in my test 🥲

**Comment by barelyhuman** [comment]
> adding a single quote makes curl simply ignore that header in my test 🥲

hmm, it's mac specific, the normal script works fine on Vercel so `linux-amd64` , i'll see what I can do

**Comment by egoist** [comment]
still can't reproduce this error, tried on both my mac and a fresh docker alpine container:

CleanShot 2021-12-04 at 17 44 43@2x

**Comment by barelyhuman** [comment]
could you try with the new patch ? https://patch-diff.githubusercontent.com/raw/egoist/bina/pull/5.patch

The auth header seems to be going for me and the redirection to the tarball worked fine

**Comment by egoist** [comment]
nope, got 404 for private repo

**Comment by barelyhuman** [comment]
I get the same responses without my change and with my change.... 

Edit: these are for a private repo

Screenshot 2021-12-04 at 3 46 02 PM
Screenshot 2021-12-04 at 3 48 34 PM

**Comment by barelyhuman** [comment]
It works, 
it was an issue with how I was setting the base `GITHUB_TOKEN` since the .env file doesn't work as expected in M1 systems. 

ended up using `source .env` and it worked as expected, same for private repos. 
It's all good, 

Closing this.

**Pull request closed without merging**
